{{- if .Values.sfapm.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "sfapm.fullname" . }}-ingress
  namespace: {{ .Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: snappyflow-apm
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "sfapm.fullname" . }}-ui
          servicePort: 80

      - path: /snappyflow
        backend:
          serviceName: {{ include "sfapm.fullname" . }}-apm
          servicePort: 8000
      - path: /user
        backend:
          serviceName: {{ include "sfapm.fullname" . }}-apm
          servicePort: 8000
      - path: /login/
        backend:
          serviceName: {{ include "sfapm.fullname" . }}-apm
          servicePort: 8000
      - path: /sso
        backend:
          serviceName: {{ include "sfapm.fullname" . }}-apm
          servicePort: 8000
      - path: /vizbuilder
        backend:
          serviceName: {{ include "sfapm.fullname" . }}-vizbuilder
          servicePort: 8000
      - path: /alert
        backend:
          serviceName: {{ include "sfapm.fullname" . }}-vizbuilder
          servicePort: 8000
      - path: /deployments
        backend:
          serviceName: {{ include "sfapm.fullname" . }}-vizbuilder
          servicePort: 8000
      - path: /logoperation
        backend:
          serviceName: {{ include "sfapm.fullname" . }}-vizbuilder
          servicePort: 8000
{{- end }}