{{- if .Values.perf_test.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kafka.fullname" . }}-kafka-perftest
  labels:
    app: {{ template "kafka.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "kafka.name" . }}-kafka-perftest
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kafka.name" . }}-kafka-perftest
        release: {{ .Release.Name }}
        {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
        {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    spec:
      containers:
      - name: producer
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: IfNotPresent
        resources:
{{ toYaml .Values.perf_test.resources | indent 14 }}
        env:
        - name: BOOTSTRAP_BROKERS
          value: "{{ include "kafka.fullname" . }}-headless:9092"
        command:
        - sh
        - -exc
        - |
          while true;do /usr/bin/kafka-producer-perf-test --num-records {{ .Values.perf_test.num_messages }} --topic {{ .Values.perf_test.topic }} --throughput {{ .Values.perf_test.throughput }} --record-size 10 --producer-props bootstrap.servers=${BOOTSTRAP_BROKERS} --print-metrics; done
      - name: consumer
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: IfNotPresent
        resources:
{{ toYaml .Values.perf_test.resources | indent 14 }}
        env:
        - name: BOOTSTRAP_BROKERS
          value: "{{ include "kafka.fullname" . }}-headless:9092"
        command:
        - sh
        - -exc
        - |
          while true;do /usr/bin/kafka-consumer-perf-test --topic {{ .Values.perf_test.topic }} --broker-list bootstrap.servers=${BOOTSTRAP_BROKERS} --messages {{ .Values.perf_test.num_messages }} --group {{ .Values.perf_test.group_name }}; done
{{- end }}
