apiVersion: {{ if .Values.common.stateful.enabled }}apps/v1{{ else }}apps/v1{{ end }}
kind: {{ if .Values.common.stateful.enabled }}StatefulSet{{ else }}Deployment{{ end }}
metadata:
  name: {{ template "fullname" . }}-data
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
    {{ default "snappyflow/appName" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectName" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    role: data
spec:
  {{- if .Values.common.stateful.enabled }}
  serviceName: {{ template "fullname" . }}-data
  {{- end }}
  replicas: {{ .Values.data.replicas }}
  selector:
    matchLabels:
      release: "{{ .Release.Name }}"
      component: {{ template "fullname" . }}
      role: data
      service: ES
      {{ default "snappyflow/appName" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
      {{ default "snappyflow/projectName" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
  template:
    metadata:
      labels:
        release: "{{ .Release.Name }}"
        component: {{ template "fullname" . }}
        role: data
        service: ES
        {{ default "snappyflow/appName" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
        {{ default "snappyflow/projectName" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if eq .Values.data.antiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  component: {{ template "fullname" . }}
                  role: data
      {{- else if eq .Values.data.antiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  component: {{ template "fullname" . }}
                  role: data
      {{- end }}
      initContainers:
      - name: init-sysctl
        image: "{{ .Values.image.init.repository }}:{{ .Values.image.init.tag }}"
        imagePullPolicy: {{ .Values.image.init.pullPolicy }}
        command: ["sh", "-c", "sysctl -w vm.max_map_count=262144 && mkdir -p /var/log/elasticsearch && chmod 777 /var/log/elasticsearch"]
        securityContext:
          privileged: true
        volumeMounts:
          - name: varlog
            mountPath: /var/log
      containers:
      - name: es-data
        securityContext:
          privileged: {{ .Values.common.stateful.enabled }}
          capabilities:
            add:
              {{- if .Values.common.stateful.enabled }}
              - IPC_LOCK
              {{- else }}
              - IPC_LOCK
              - SYS_RESOURCE
              {{- end }}
        image: "{{ .Values.image.es.repository }}:{{ .Values.image.es.tag }}"
        imagePullPolicy: {{ .Values.image.es.pullPolicy }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DISCOVERY_SERVICE
          value: {{ template "fullname" . }}-discovery
        - name: ES_JAVA_OPTS
          value: "-Xms{{ .Values.data.heapMemory }} -Xmx{{ .Values.data.heapMemory }}"
        {{- range $key, $value :=  .Values.common.env }}
        - name: {{ $key | upper | replace "-" "_" }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value :=  .Values.data.env }}
        - name: {{ $key | upper | replace "-" "_" }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
{{ toYaml .Values.data.resources | indent 10 }}
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 9300
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: logconfig
          mountPath: /elasticsearch/config/log4j2.properties
          subPath: log4j2.properties
        - name: varlog
          mountPath: /var/log
{{- if .Values.logger.enabled }}
      - name: {{ template "fullname" . }}-data-logger
        image:  "{{ .Values.logger.image }}:{{ .Values.logger.imageTag }}"
        imagePullPolicy: {{ .Values.logger.imagePullPolicy | quote }}
        command:
        - /app/sfagent
        - -config
        - '{"key":"{{ .Values.global.key }}","logging":{"plugins":[{"name":"elasticsearch-general","enabled":true,"config":{"log_level":["info","debug","error"],"log_path":"/var/log/elasticsearch/*"}}]}}'
        env:
        - name: APP_NAME
          value: {{ .Values.global.sfappname }}
        - name: PROJECT_NAME
          value: {{ .Values.global.sfprojectname }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
{{- end }}
      volumes:
        - name: logconfig
          configMap:
            name: {{ template "fullname" . }}
        - name: varlog
          emptyDir: {}
        - name: libsystemddir
          hostPath:
            path: /usr/lib64
      {{- if not .Values.common.stateful.enabled }}
        - emptyDir:
            medium: ""
          name: "storage"
      {{- end }}
  {{- if .Values.common.stateful.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        volume.beta.kubernetes.io/storage-class: {{ .Values.common.stateful.class }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.data.stateful.size }}
  {{- end }}
