apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hive.fullname" . }}-metastore
  labels:
    {{- include "hive.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hive.name" . }}-metastore
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "hive.name" . }}-metastore
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
        {{ .Values.global.snappyflowProjectLabel}}: {{ .Values.global.snappyflowProjectName }}
        {{ .Values.global.snappyflowAppLabel }}: {{ .Values.global.snappyflowAppName }}
    spec:
      priorityClassName: {{ .Release.Name }}-priority-class
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and (eq .Values.global.secrets.aws.enable true) (eq .Values.global.secrets.aws.use_iam_role true) }}
      serviceAccountName: {{ .Release.Name }}-service-account
      {{- end}}
      initContainers:
        - name: db-ready
          image: "bitnami/postgresql:11.5.0-debian-9-r34"
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - "until pg_isready -d postgresql://'{{ .Values.global.postgresql.postgresqlUsername }}':'{{ .Values.global.postgresql.postgresqlPassword }}'@'{{ template "hive.postgresql.fullname" . }}':{{ .Values.global.postgresql.servicePort }}/'hive_metastore'; do sleep 3; done"
        - name: namenode-ready
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup {{ include "hadoop.namenode.service" . }}; do echo waiting for namenode; sleep 2; done"]
        - name: datanode-ready
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup {{ include "hadoop.datanode.service" . }}; do echo waiting for datanode; sleep 2; done"]
      containers:
        - name: metastore
          image: "{{ .Values.image.hiveMetastore.repository }}:{{ .Values.image.hiveMetastore.tag }}"
          imagePullPolicy: {{ .Values.image.hiveMetastore.pullPolicy }}
          ports:
            - name: metastore
              containerPort: {{ .Values.service.hiveMetastore.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ template "hive-and-hadoop.fullname" . }}-env
          env:
            - name: HADOOP_HEAPSIZE
              value: "384"
            {{- if (eq .Values.global.secrets.gcs.enable true) }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            {{- end }}
            {{- if (eq .Values.global.secrets.aws.enable true) }}
            {{- if (eq .Values.global.secrets.aws.use_iam_role false) }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.global.secrets.aws.AWS_ACCESS_KEY_ID }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.global.secrets.aws.AWS_SECRET_ACCESS_KEY }}
            - name: AWS_REGION
              value: {{ .Values.global.secrets.aws.AWS_DEFAULT_REGION }}
            {{- end }}
            {{- end }}
          startupProbe:
            tcpSocket:
              port: metastore
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 20
            timeoutSeconds: 9
          livenessProbe:
            tcpSocket:
              port: metastore
            initialDelaySeconds: 300
            periodSeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
{{- toYaml .Values.containerResources.hiveMetastore | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
