apiVersion: v1
appVersion: 2.1.0.BUILD-SNAPSHOT
description: Helm chart for deploying basic Spring applications
name: petclinic-v3
keywords:
- spring
- petclinic
- v3
home: https://spring.io
icon: https://spring.io/img/homepage/icon-spring-boot.svg
sources:
  - https://github.com/spring-projects/spring-petclinic
version: 0.4.0
